spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: user_data
      org:
        hibernate:
          envers:
            default_schema: audit
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-79-125-4-72.eu-west-1.compute.amazonaws.com:5432/d5kkgrqqmj0jor
    username: cypwhgedirxuch
    password: 0ee174aa3cbf9d8febbaa0cb6c93a918e283e9f62b0968a46d93f82d9f49104f
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: user_data
    url: jdbc:postgresql://ec2-79-125-4-72.eu-west-1.compute.amazonaws.com:5432/d5kkgrqqmj0jor
    user: cypwhgedirxuch
    password: 0ee174aa3cbf9d8febbaa0cb6c93a918e283e9f62b0968a46d93f82d9f49104f
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging:
  level:
    com.me.storyhubuserrepositorybackend: TRACE
