

spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: user_data
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: user_data
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging:
  level:
    com.me.storyhubuserrepositorybackend: TRACE
server:
  port: 9410
